/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inventory;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
    	
    	Scanner scanner = new Scanner(System.in);
    	
        System.out.println("Hi! Please enter an item name:" );
        String name = scanner.next();
        System.out.println("Please enter the item's serial number:" );
        String serialNo = scanner.next();
        System.out.println("Lastly, please enter the item's value:" );
        double value = scanner.nextDouble();
        
        scanner.close();
        
        Item item = new Item(name, serialNo, value);
        
        System.out.println("The item's name is: " + item.getName());
        System.out.println("The item's serial number is: " + item.getSerialNo());
        System.out.println("The item's value is: " + item.getValue());
    }
}
